BEGIN;

USE WAREHOUSE DATALOADING;
USE DATABASE PRODUCTION_DATAFEEDS;

CREATE SCHEMA PRODUCTION_DATAFEEDS.ERA;
USE SCHEMA ERA;

CREATE FILE FORMAT "PRODUCTION_DATAFEEDS"."ERA"."PARQUET_FORMAT" TYPE =  PARQUET;

CREATE OR REPLACE TABLE "ERA5_RAW_MANIFEST" (
"LATITUDE" NUMBER(9,6) NOT NULL,
"LONGITUDE" NUMBER(9,6) NOT NULL,
"GEO_SUBSET" TEXT NOT NULL,
PRIMARY KEY("LATITUDE", "LONGITUDE")
);

CREATE OR REPLACE TABLE "ERA5_RAW" (
"LATITUDE" NUMBER(9,6) NOT NULL,
"LONGITUDE" NUMBER(9,6) NOT NULL,
"TIME" TIMESTAMP_NTZ NOT NULL,
"T2M" DOUBLE NOT NULL,
"U100" DOUBLE NOT NULL,
"V100" DOUBLE NOT NULL,
"U10" DOUBLE NOT NULL,
"V10" DOUBLE NOT NULL,
"SSR" DOUBLE NOT NULL,
"SSRD" DOUBLE NOT NULL,
"FDIR" DOUBLE NOT NULL,
"CDIR" DOUBLE NOT NULL,
"SSRDC" DOUBLE NOT NULL,
"ASN" DOUBLE NOT NULL,
"MTPR" DOUBLE NOT NULL,
"PTYPE" DOUBLE NOT NULL,
"TCC" DOUBLE NOT NULL,
"TP" DOUBLE NOT NULL,
"SD" DOUBLE NOT NULL,
"SF" DOUBLE NOT NULL,
"SKT" DOUBLE NOT NULL,
"TCWV" DOUBLE NOT NULL,
PRIMARY KEY("TIME", "LATITUDE", "LONGITUDE")
);

CREATE OR REPLACE TABLE "ERA5_WIND_DOWNSCALED_MANIFEST"(
"LATITUDE" NUMBER(9,6) NOT NULL,
"LONGITUDE" NUMBER(9,6) NOT NULL,
"HEIGHT" NUMBER(9,6) NOT NULL,
"DOWNSCALE" TEXT NOT NULL,
"SHEAR" TEXT NOT NULL,
"ELEVATION" DOUBLE NOT NULL,
"AIR_DENSITY" DOUBLE NOT NULL,
"ERA_DOWNSCALED_ID" INT AUTOINCREMENT INCREMENT 1,
PRIMARY KEY("LATITUDE", "LONGITUDE", "HEIGHT", "DOWNSCALE", "SHEAR")
);

CREATE OR REPLACE TABLE "ERA5_WIND_DOWNSCALED"(
"ERA_DOWNSCALED_ID" INT NOT NULL,
"TIME" TIMESTAMP_NTZ NOT NULL,
"WIND_SPEED_MS" DOUBLE NOT NULL,
"WIND_DIRECTION" DOUBLE NOT NULL,
"TEMP2M_K" DOUBLE NOT NULL,
PRIMARY KEY("ERA_DOWNSCALED_ID", "TIME")
);

/-- One time bulk load from S3
 CREATE OR REPLACE STAGE ERA%_RAW_STAGE
  url='s3://resurety-nonproprietary-datafeeds/reanalysis/era5/processed/' credentials=(aws_key_id='<aws_public_key>'
   aws_secret_key='<aws_private_key>')
  file_format = PARQUET_FORMAT;

COPY INTO ERA5_RAW FROM
(SELECT
$1:LATITUDE::NUMBER(9,6),
$1:LONGITUDE::NUMBER(9,6),
$1:TIME::TIMESTAMP_NTZ(9),
$1:T2M::FLOAT,
$1:U100::FLOAT,
$1:V100::FLOAT,
$1:U10::FLOAT,
$1:V10::FLOAT,
$1:SSR::FLOAT,
$1:SSRD::FLOAT,
$1:FDIR::FLOAT,
$1:CDIR::FLOAT,
$1:SSRDC::FLOAT,
$1:ASN::FLOAT,
$1:MTPR::FLOAT,
$1:PTYPE::FLOAT,
$1:TCC::FLOAT,
$1:TP::FLOAT,
$1:SD::FLOAT,
$1:SF::FLOAT,
$1:SKT::FLOAT,
$1:TCWV::FLOAT
 FROM  @era5_raw_stage/);

COMMIT;